# Generated by Django 3.1.1 on 2020-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebook', '0003_auto_20201002_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='some shit', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, help_text='help text', max_length=50, verbose_name='Название'),
        ),
    ]
